version: '3.8'

services:
  postgres:
    image: postgres:15-bullseye
    container_name: werewolf-postgres-dev
    environment:
      POSTGRES_DB: werewolf_dev
      POSTGRES_USER: werewolf
      POSTGRES_PASSWORD: werewolf123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ✅ CORRIGIDO: Caminho correto para o init.sql na raiz
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - werewolf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U werewolf -d werewolf_dev"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-bullseye
    container_name: werewolf-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - werewolf-network
    healthcheck:
      # ✅ CORRIGIDO: redis-cli ping não precisa de -h ou -p dentro da rede Docker
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: werewolf-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://werewolf:werewolf123@postgres:5432/werewolf_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-super-secret-jwt-key-for-development-only
    ports:
      - "3001:3001"
      - "9229:9229" # Para debug, se necessário
    volumes:
      # ✅ CORRIGIDO: Mapeia apenas a pasta 'src' do backend para hot-reloading
      # O WORKDIR no Dockerfile já nos coloca em /usr/src/app/backend
      - ./backend/src:/usr/src/app/backend/src
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - werewolf-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:

networks:
  werewolf-network:
    driver: bridge